### PR TITLE
Snippet cleanup

### PR DESCRIPTION
**Pull request by HorizonShadow**
Because in line event handlers make me sick to my stomach.

### CODE REVIEW

**Comment by awalGarg** [comment]
haven't read or tested the changes. can haz quick explanation? Also, AFAIK, there aren't any inline event handlers anywhere in the codebase

**Comment by HorizonShadow** [comment]
`addEventlistener('click', function(e) {})` to `Snip.UI.onThingClick = function (e) }{}`.

**Comment by awalGarg** [comment]
ah, well. I hope you took care of context managing? since some of those functions rely on `this` val

**Comment by HorizonShadow** [comment]
I think I missed on in the search handler. I would test this, but installing php and composer on windows has turned into a headache. Uno momento

**Pull request merged**
